// JSCAD v2 generated by Ergogen
const { booleans, primitives, extrusions, transforms, measurements } = require('@jscad/modeling')

    function export_extrude_1_outline_fn(){
        return extrusions.extrudeLinear({height: 1}, primitives.polygon({points: [[-9, -9], [9, -9], [9, 9], [-9, 9]]}));
    }



                function _export_case_fn() {
                    

                // creating part 0 of case _export
                let _export__part_0 = export_extrude_1_outline_fn();

                // make sure that rotations are relative to the center
                const _export__part_0_bounds = measurements.measureBoundingBox(_export__part_0);
                const _export__part_0_bounds_center = [
                    (_export__part_0_bounds[0][0] + _export__part_0_bounds[1][0]) / 2,
                    (_export__part_0_bounds[0][1] + _export__part_0_bounds[1][1]) / 2,
                    (_export__part_0_bounds[0][2] + _export__part_0_bounds[1][2]) / 2
                ];
                
                // translate to origin for rotation
                _export__part_0 = transforms.translate([-_export__part_0_bounds_center[0], -_export__part_0_bounds_center[1], -_export__part_0_bounds_center[2]], _export__part_0);
                
                // apply rotation
                if ([0,0,0][0] !== 0) _export__part_0 = transforms.rotateX([0,0,0][0] * Math.PI / 180, _export__part_0);
                if ([0,0,0][1] !== 0) _export__part_0 = transforms.rotateY([0,0,0][1] * Math.PI / 180, _export__part_0);
                if ([0,0,0][2] !== 0) _export__part_0 = transforms.rotateZ([0,0,0][2] * Math.PI / 180, _export__part_0);
                
                // translate back from origin
                _export__part_0 = transforms.translate([_export__part_0_bounds_center[0], _export__part_0_bounds_center[1], _export__part_0_bounds_center[2]], _export__part_0);

                // apply additional shift
                _export__part_0 = transforms.translate([0,0,0], _export__part_0);
                
            
                // combine all parts using JSCAD v2 boolean operations
                let result = _export__part_0;

                    return result;
                }
            
            
        
            function main() {
                return _export_case_fn();
            }

            module.exports = { main }

        