// JSCAD v2 generated by Ergogen
const { booleans, primitives, extrusions, transforms, measurements } = require('@jscad/modeling')

    function square_extrude_5_outline_fn(){
        return extrusions.extrudeLinear({height: 5}, primitives.polygon({points: [[-2.5, -2.5], [2.5, -2.5], [2.5, 2.5], [-2.5, 2.5]]}));
    }



                function cube_case_fn() {
                    

                // creating part 0 of case cube
                let cube__part_0 = square_extrude_5_outline_fn();

                // make sure that rotations are relative to the center
                const cube__part_0_bounds = measurements.measureBoundingBox(cube__part_0);
                const cube__part_0_bounds_center = [
                    (cube__part_0_bounds[0][0] + cube__part_0_bounds[1][0]) / 2,
                    (cube__part_0_bounds[0][1] + cube__part_0_bounds[1][1]) / 2,
                    (cube__part_0_bounds[0][2] + cube__part_0_bounds[1][2]) / 2
                ];
                
                // translate to origin for rotation
                cube__part_0 = transforms.translate([-cube__part_0_bounds_center[0], -cube__part_0_bounds_center[1], -cube__part_0_bounds_center[2]], cube__part_0);
                
                // apply rotation
                if ([0,0,0][0] !== 0) cube__part_0 = transforms.rotateX([0,0,0][0] * Math.PI / 180, cube__part_0);
                if ([0,0,0][1] !== 0) cube__part_0 = transforms.rotateY([0,0,0][1] * Math.PI / 180, cube__part_0);
                if ([0,0,0][2] !== 0) cube__part_0 = transforms.rotateZ([0,0,0][2] * Math.PI / 180, cube__part_0);
                
                // translate back from origin
                cube__part_0 = transforms.translate([cube__part_0_bounds_center[0], cube__part_0_bounds_center[1], cube__part_0_bounds_center[2]], cube__part_0);

                // apply additional shift
                cube__part_0 = transforms.translate([0,0,0], cube__part_0);
                
            
                // combine all parts using JSCAD v2 boolean operations
                let result = cube__part_0;

                    return result;
                }
            
            
        
            function main() {
                return cube_case_fn();
            }

            module.exports = { main }

        