// JSCAD v2 generated by Ergogen
const { booleans, primitives, extrusions, transforms, measurements } = require('@jscad/modeling')

    function _square_extrude_8_outline_fn(){
        return extrusions.extrudeLinear({height: 8}, primitives.polygon({points: [[-4, -4], [4, -4], [4, 4], [-4, 4]]}));
    }

    function _circle_extrude_8_outline_fn(){
        return extrusions.extrudeLinear({height: 8}, primitives.circle({center: [0, 0], radius: 3}));
    }

    function _square_extrude_1_outline_fn(){
        return extrusions.extrudeLinear({height: 1}, primitives.polygon({points: [[-4, -4], [4, -4], [4, 4], [-4, 4]]}));
    }



                function _subtract_case_fn() {
                    

                // creating part target of case _subtract
                let _subtract__part_target = _cube_case_fn();

                // make sure that rotations are relative to the center
                const _subtract__part_target_bounds = measurements.measureBoundingBox(_subtract__part_target);
                const _subtract__part_target_bounds_center = [
                    (_subtract__part_target_bounds[0][0] + _subtract__part_target_bounds[1][0]) / 2,
                    (_subtract__part_target_bounds[0][1] + _subtract__part_target_bounds[1][1]) / 2,
                    (_subtract__part_target_bounds[0][2] + _subtract__part_target_bounds[1][2]) / 2
                ];
                
                // translate to origin for rotation
                _subtract__part_target = transforms.translate([-_subtract__part_target_bounds_center[0], -_subtract__part_target_bounds_center[1], -_subtract__part_target_bounds_center[2]], _subtract__part_target);
                
                // apply rotation
                if ([0,0,0][0] !== 0) _subtract__part_target = transforms.rotateX([0,0,0][0] * Math.PI / 180, _subtract__part_target);
                if ([0,0,0][1] !== 0) _subtract__part_target = transforms.rotateY([0,0,0][1] * Math.PI / 180, _subtract__part_target);
                if ([0,0,0][2] !== 0) _subtract__part_target = transforms.rotateZ([0,0,0][2] * Math.PI / 180, _subtract__part_target);
                
                // translate back from origin
                _subtract__part_target = transforms.translate([_subtract__part_target_bounds_center[0], _subtract__part_target_bounds_center[1], _subtract__part_target_bounds_center[2]], _subtract__part_target);

                // apply additional shift
                _subtract__part_target = transforms.translate([0,0,0], _subtract__part_target);
                
            

                // creating part tool of case _subtract
                let _subtract__part_tool = _cylinder_one_case_fn();

                // make sure that rotations are relative to the center
                const _subtract__part_tool_bounds = measurements.measureBoundingBox(_subtract__part_tool);
                const _subtract__part_tool_bounds_center = [
                    (_subtract__part_tool_bounds[0][0] + _subtract__part_tool_bounds[1][0]) / 2,
                    (_subtract__part_tool_bounds[0][1] + _subtract__part_tool_bounds[1][1]) / 2,
                    (_subtract__part_tool_bounds[0][2] + _subtract__part_tool_bounds[1][2]) / 2
                ];
                
                // translate to origin for rotation
                _subtract__part_tool = transforms.translate([-_subtract__part_tool_bounds_center[0], -_subtract__part_tool_bounds_center[1], -_subtract__part_tool_bounds_center[2]], _subtract__part_tool);
                
                // apply rotation
                if ([0,0,0][0] !== 0) _subtract__part_tool = transforms.rotateX([0,0,0][0] * Math.PI / 180, _subtract__part_tool);
                if ([0,0,0][1] !== 0) _subtract__part_tool = transforms.rotateY([0,0,0][1] * Math.PI / 180, _subtract__part_tool);
                if ([0,0,0][2] !== 0) _subtract__part_tool = transforms.rotateZ([0,0,0][2] * Math.PI / 180, _subtract__part_tool);
                
                // translate back from origin
                _subtract__part_tool = transforms.translate([_subtract__part_tool_bounds_center[0], _subtract__part_tool_bounds_center[1], _subtract__part_tool_bounds_center[2]], _subtract__part_tool);

                // apply additional shift
                _subtract__part_tool = transforms.translate([0,0,0], _subtract__part_tool);
                
            
                // combine all parts using JSCAD v2 boolean operations
                let result = _subtract__part_target;
                result = booleans.subtract(result, _subtract__part_tool);

                    return result;
                }
            
            

                function _cube_case_fn() {
                    

                // creating part 0 of case _cube
                let _cube__part_0 = _square_extrude_8_outline_fn();

                // make sure that rotations are relative to the center
                const _cube__part_0_bounds = measurements.measureBoundingBox(_cube__part_0);
                const _cube__part_0_bounds_center = [
                    (_cube__part_0_bounds[0][0] + _cube__part_0_bounds[1][0]) / 2,
                    (_cube__part_0_bounds[0][1] + _cube__part_0_bounds[1][1]) / 2,
                    (_cube__part_0_bounds[0][2] + _cube__part_0_bounds[1][2]) / 2
                ];
                
                // translate to origin for rotation
                _cube__part_0 = transforms.translate([-_cube__part_0_bounds_center[0], -_cube__part_0_bounds_center[1], -_cube__part_0_bounds_center[2]], _cube__part_0);
                
                // apply rotation
                if ([0,0,0][0] !== 0) _cube__part_0 = transforms.rotateX([0,0,0][0] * Math.PI / 180, _cube__part_0);
                if ([0,0,0][1] !== 0) _cube__part_0 = transforms.rotateY([0,0,0][1] * Math.PI / 180, _cube__part_0);
                if ([0,0,0][2] !== 0) _cube__part_0 = transforms.rotateZ([0,0,0][2] * Math.PI / 180, _cube__part_0);
                
                // translate back from origin
                _cube__part_0 = transforms.translate([_cube__part_0_bounds_center[0], _cube__part_0_bounds_center[1], _cube__part_0_bounds_center[2]], _cube__part_0);

                // apply additional shift
                _cube__part_0 = transforms.translate([0,0,0], _cube__part_0);
                
            
                // combine all parts using JSCAD v2 boolean operations
                let result = _cube__part_0;

                    return result;
                }
            
            

                function _cylinder_one_case_fn() {
                    

                // creating part 0 of case _cylinder_one
                let _cylinder_one__part_0 = _circle_extrude_8_outline_fn();

                // make sure that rotations are relative to the center
                const _cylinder_one__part_0_bounds = measurements.measureBoundingBox(_cylinder_one__part_0);
                const _cylinder_one__part_0_bounds_center = [
                    (_cylinder_one__part_0_bounds[0][0] + _cylinder_one__part_0_bounds[1][0]) / 2,
                    (_cylinder_one__part_0_bounds[0][1] + _cylinder_one__part_0_bounds[1][1]) / 2,
                    (_cylinder_one__part_0_bounds[0][2] + _cylinder_one__part_0_bounds[1][2]) / 2
                ];
                
                // translate to origin for rotation
                _cylinder_one__part_0 = transforms.translate([-_cylinder_one__part_0_bounds_center[0], -_cylinder_one__part_0_bounds_center[1], -_cylinder_one__part_0_bounds_center[2]], _cylinder_one__part_0);
                
                // apply rotation
                if ([0,0,0][0] !== 0) _cylinder_one__part_0 = transforms.rotateX([0,0,0][0] * Math.PI / 180, _cylinder_one__part_0);
                if ([0,0,0][1] !== 0) _cylinder_one__part_0 = transforms.rotateY([0,0,0][1] * Math.PI / 180, _cylinder_one__part_0);
                if ([0,0,0][2] !== 0) _cylinder_one__part_0 = transforms.rotateZ([0,0,0][2] * Math.PI / 180, _cylinder_one__part_0);
                
                // translate back from origin
                _cylinder_one__part_0 = transforms.translate([_cylinder_one__part_0_bounds_center[0], _cylinder_one__part_0_bounds_center[1], _cylinder_one__part_0_bounds_center[2]], _cylinder_one__part_0);

                // apply additional shift
                _cylinder_one__part_0 = transforms.translate([0,0,0], _cylinder_one__part_0);
                
            
                // combine all parts using JSCAD v2 boolean operations
                let result = _cylinder_one__part_0;

                    return result;
                }
            
            

                function _cylinder_two_case_fn() {
                    

                // creating part 0 of case _cylinder_two
                let _cylinder_two__part_0 = _circle_extrude_8_outline_fn();

                // make sure that rotations are relative to the center
                const _cylinder_two__part_0_bounds = measurements.measureBoundingBox(_cylinder_two__part_0);
                const _cylinder_two__part_0_bounds_center = [
                    (_cylinder_two__part_0_bounds[0][0] + _cylinder_two__part_0_bounds[1][0]) / 2,
                    (_cylinder_two__part_0_bounds[0][1] + _cylinder_two__part_0_bounds[1][1]) / 2,
                    (_cylinder_two__part_0_bounds[0][2] + _cylinder_two__part_0_bounds[1][2]) / 2
                ];
                
                // translate to origin for rotation
                _cylinder_two__part_0 = transforms.translate([-_cylinder_two__part_0_bounds_center[0], -_cylinder_two__part_0_bounds_center[1], -_cylinder_two__part_0_bounds_center[2]], _cylinder_two__part_0);
                
                // apply rotation
                if ([90,0,0][0] !== 0) _cylinder_two__part_0 = transforms.rotateX([90,0,0][0] * Math.PI / 180, _cylinder_two__part_0);
                if ([90,0,0][1] !== 0) _cylinder_two__part_0 = transforms.rotateY([90,0,0][1] * Math.PI / 180, _cylinder_two__part_0);
                if ([90,0,0][2] !== 0) _cylinder_two__part_0 = transforms.rotateZ([90,0,0][2] * Math.PI / 180, _cylinder_two__part_0);
                
                // translate back from origin
                _cylinder_two__part_0 = transforms.translate([_cylinder_two__part_0_bounds_center[0], _cylinder_two__part_0_bounds_center[1], _cylinder_two__part_0_bounds_center[2]], _cylinder_two__part_0);

                // apply additional shift
                _cylinder_two__part_0 = transforms.translate([0,4,4], _cylinder_two__part_0);
                
            
                // combine all parts using JSCAD v2 boolean operations
                let result = _cylinder_two__part_0;

                    return result;
                }
            
            

                function _flat_square_case_fn() {
                    

                // creating part 0 of case _flat_square
                let _flat_square__part_0 = _square_extrude_1_outline_fn();

                // make sure that rotations are relative to the center
                const _flat_square__part_0_bounds = measurements.measureBoundingBox(_flat_square__part_0);
                const _flat_square__part_0_bounds_center = [
                    (_flat_square__part_0_bounds[0][0] + _flat_square__part_0_bounds[1][0]) / 2,
                    (_flat_square__part_0_bounds[0][1] + _flat_square__part_0_bounds[1][1]) / 2,
                    (_flat_square__part_0_bounds[0][2] + _flat_square__part_0_bounds[1][2]) / 2
                ];
                
                // translate to origin for rotation
                _flat_square__part_0 = transforms.translate([-_flat_square__part_0_bounds_center[0], -_flat_square__part_0_bounds_center[1], -_flat_square__part_0_bounds_center[2]], _flat_square__part_0);
                
                // apply rotation
                if ([0,0,0][0] !== 0) _flat_square__part_0 = transforms.rotateX([0,0,0][0] * Math.PI / 180, _flat_square__part_0);
                if ([0,0,0][1] !== 0) _flat_square__part_0 = transforms.rotateY([0,0,0][1] * Math.PI / 180, _flat_square__part_0);
                if ([0,0,0][2] !== 0) _flat_square__part_0 = transforms.rotateZ([0,0,0][2] * Math.PI / 180, _flat_square__part_0);
                
                // translate back from origin
                _flat_square__part_0 = transforms.translate([_flat_square__part_0_bounds_center[0], _flat_square__part_0_bounds_center[1], _flat_square__part_0_bounds_center[2]], _flat_square__part_0);

                // apply additional shift
                _flat_square__part_0 = transforms.translate([0,0,0], _flat_square__part_0);
                
            
                // combine all parts using JSCAD v2 boolean operations
                let result = _flat_square__part_0;

                    return result;
                }
            
            

                function combination_case_fn() {
                    

                // creating part 0 of case combination
                let combination__part_0 = _subtract_case_fn();

                // make sure that rotations are relative to the center
                const combination__part_0_bounds = measurements.measureBoundingBox(combination__part_0);
                const combination__part_0_bounds_center = [
                    (combination__part_0_bounds[0][0] + combination__part_0_bounds[1][0]) / 2,
                    (combination__part_0_bounds[0][1] + combination__part_0_bounds[1][1]) / 2,
                    (combination__part_0_bounds[0][2] + combination__part_0_bounds[1][2]) / 2
                ];
                
                // translate to origin for rotation
                combination__part_0 = transforms.translate([-combination__part_0_bounds_center[0], -combination__part_0_bounds_center[1], -combination__part_0_bounds_center[2]], combination__part_0);
                
                // apply rotation
                if ([0,0,0][0] !== 0) combination__part_0 = transforms.rotateX([0,0,0][0] * Math.PI / 180, combination__part_0);
                if ([0,0,0][1] !== 0) combination__part_0 = transforms.rotateY([0,0,0][1] * Math.PI / 180, combination__part_0);
                if ([0,0,0][2] !== 0) combination__part_0 = transforms.rotateZ([0,0,0][2] * Math.PI / 180, combination__part_0);
                
                // translate back from origin
                combination__part_0 = transforms.translate([combination__part_0_bounds_center[0], combination__part_0_bounds_center[1], combination__part_0_bounds_center[2]], combination__part_0);

                // apply additional shift
                combination__part_0 = transforms.translate([0,0,0], combination__part_0);
                
            

                // creating part 1 of case combination
                let combination__part_1 = _cylinder_two_case_fn();

                // make sure that rotations are relative to the center
                const combination__part_1_bounds = measurements.measureBoundingBox(combination__part_1);
                const combination__part_1_bounds_center = [
                    (combination__part_1_bounds[0][0] + combination__part_1_bounds[1][0]) / 2,
                    (combination__part_1_bounds[0][1] + combination__part_1_bounds[1][1]) / 2,
                    (combination__part_1_bounds[0][2] + combination__part_1_bounds[1][2]) / 2
                ];
                
                // translate to origin for rotation
                combination__part_1 = transforms.translate([-combination__part_1_bounds_center[0], -combination__part_1_bounds_center[1], -combination__part_1_bounds_center[2]], combination__part_1);
                
                // apply rotation
                if ([0,0,0][0] !== 0) combination__part_1 = transforms.rotateX([0,0,0][0] * Math.PI / 180, combination__part_1);
                if ([0,0,0][1] !== 0) combination__part_1 = transforms.rotateY([0,0,0][1] * Math.PI / 180, combination__part_1);
                if ([0,0,0][2] !== 0) combination__part_1 = transforms.rotateZ([0,0,0][2] * Math.PI / 180, combination__part_1);
                
                // translate back from origin
                combination__part_1 = transforms.translate([combination__part_1_bounds_center[0], combination__part_1_bounds_center[1], combination__part_1_bounds_center[2]], combination__part_1);

                // apply additional shift
                combination__part_1 = transforms.translate([0,0,0], combination__part_1);
                
            

                // creating part 2 of case combination
                let combination__part_2 = _flat_square_case_fn();

                // make sure that rotations are relative to the center
                const combination__part_2_bounds = measurements.measureBoundingBox(combination__part_2);
                const combination__part_2_bounds_center = [
                    (combination__part_2_bounds[0][0] + combination__part_2_bounds[1][0]) / 2,
                    (combination__part_2_bounds[0][1] + combination__part_2_bounds[1][1]) / 2,
                    (combination__part_2_bounds[0][2] + combination__part_2_bounds[1][2]) / 2
                ];
                
                // translate to origin for rotation
                combination__part_2 = transforms.translate([-combination__part_2_bounds_center[0], -combination__part_2_bounds_center[1], -combination__part_2_bounds_center[2]], combination__part_2);
                
                // apply rotation
                if ([0,0,0][0] !== 0) combination__part_2 = transforms.rotateX([0,0,0][0] * Math.PI / 180, combination__part_2);
                if ([0,0,0][1] !== 0) combination__part_2 = transforms.rotateY([0,0,0][1] * Math.PI / 180, combination__part_2);
                if ([0,0,0][2] !== 0) combination__part_2 = transforms.rotateZ([0,0,0][2] * Math.PI / 180, combination__part_2);
                
                // translate back from origin
                combination__part_2 = transforms.translate([combination__part_2_bounds_center[0], combination__part_2_bounds_center[1], combination__part_2_bounds_center[2]], combination__part_2);

                // apply additional shift
                combination__part_2 = transforms.translate([0,0,0], combination__part_2);
                
            
                // combine all parts using JSCAD v2 boolean operations
                let result = booleans.union(combination__part_0, combination__part_2);
                result = booleans.intersect(result, combination__part_1);

                    return result;
                }
            
            
        
            function main() {
                return combination_case_fn();
            }

            module.exports = { main }

        