units:
  pad: 1
points:
  key:
    bind: pad
  zones:
    matrix:
      columns:
        outer:
          key:
            column_net: P10
        pinky:
          key:
            column_net: P16
            stagger: .25cy
        ring:
          key:
            column_net: P14
            stagger: .66cy
        middle:
          key:
            column_net: P15
            stagger: .2cy
        index:
          key:
            column_net: P18
            stagger: -.25cy
        inner:
          key:
            column_net: P19
            stagger: -.2cy
      rows:
        bottom:
          padding: cy+.5
          row_net: P20
        middle:
          padding: cy+.5
          row_net: P21
        top:
          row_net: P4
    thumb:
      key:
      anchor:
        ref: matrix_index_bottom
        shift: [-.4cx, -1.2cy]
      columns:
        a:
          key:
            splay: -10
            column_net: P14
        b:
          key:
            splay: -10
            stagger: -.1cy
            spread: 1.15cx
            column_net: P15
        c:
          key:
            bind: [2, pad]
            splay: -10
            stagger: -.1cy
            spread: 1.15cx
            column_net: P18
        d:
          key:
            splay: -10
            stagger: -.1cy
            spread: 1.15cx
            column_net: P19
      rows:
        only:
          row_net: P9

outlines:
  keys:
    - what: rectangle
      where: true
      size: [cx, cy]
  raw:
    - what: rectangle
      where: true
      size: [cx, cy]
      bound: true
  _triangle:
    - what: polygon
      operation: add
      points:
        - ref: matrix_outer_top
          shift: [.5cx, 0]
        - ref: matrix_outer_bottom
          shift: [.5cx + pad, -.5cy - pad]
        - ref: thumb_a_only
          shift: [-.5cx - pad, -.5cy - pad]
        - ref: thumb_a_only
          shift: [.5cx, -.5cy - pad]
        - ref: thumb_d_only
          shift: [.5cx + pad, .5cy + pad]
        - ref: matrix_inner_middle
          shift: [1.75u, .1u]
        - ref: matrix_inner_top
          shift: [.5cx + pad, .5cy + pad]
  wtriangle:
    - what: outline
      name: raw
    - what: outline
      name: _triangle
  smooth1:
    - what: outline
      name: wtriangle
      fillet: 1.5
  _micro:
    - what: rectangle
      where:
        ref: matrix_inner_middle
        shift: [1.2cx, -.9u]
      size: [cx, 2u]
  _cutoutpoly:
    - what: polygon
      points:
        - ref: matrix_inner_top
          shift: [.5cx + pad, + 4u]
        - ref: matrix_inner_bottom
          shift: [.5cx + pad, -.5cy - 5]
        - ref: thumb_c_only
          shift: [.5cx + pad, .5cy + pad]
        - ref: thumb_d_only
          shift: [cx, .5cy + pad]
        - ref: matrix_inner_top
          shift: [4u, + 4u]
  pcb:
    - what: outline
      name: smooth1
    - what: outline
      name: keys
      operation: subtract
    - what: outline
      name: _micro
      operation: subtract
  sp:
    - what: outline
      name: raw
    - what: outline
      name: _triangle
    - what: outline
      name: _cutoutpoly
      operation: subtract
      fillet: 1.5
    - what: outline
      name: keys
      operation: subtract
  sp_large:
    - what: polygon
      points:
        - ref: matrix_outer_top
          shift: [-.5cx - pad, pad + 1.61cy]
        - ref: matrix_inner_top
          shift: [.5cx + pad, pad + .95cy]
        - ref: thumb_d_only
          shift: [.5cx + pad, pad + .5cy]
        - ref: thumb_d_only
          shift: [.5cx + pad, -pad - .5cy]
        - ref: matrix_outer_bottom
          shift: [-.5cx - pad, -.5cy - pad]
      fillet: 6
    - what: outline
      name: keys
      operation: subtract
pcbs:
  fourne:
    outlines:
      main:
        outline: smooth1
    footprints:
      mcu:
        what: promicro_pretty
        where:
          ref: matrix_inner_middle
          shift: [1.2cx, -.9u]
          rotate: -90
      keys:
        what: choc
        where: true
        params:
          from: "{{colrow}}"
          to: "{{column_net}}"
          keycaps: true
          hotswap: true
          reverse: true
      diodes:
        what: diode
        where: true
        adjust:
          shift: [0, -5]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
      reset:
        what: b3u1000p
        where:
          ref: matrix_inner_top
          shift: [.9cx, -.5cy]
        params:
          r1: RST
          r2: GND
      niceview:
        what: oled-reversible
        where:
          ref: matrix_inner_middle
          shift: [1.2cx - 6, -.9u - 19]
          rotate: 90
        params:
          side: "F"
          SDA: P2
          SCL: P3
          VCC: VCC
          GND: GND
      slider:
        what: pcm12
        where:
          ref: thumb_d_only
          shift: [-.2cx, 1u]
          rotate: 139.5
        params:
          from: "pos"
          to: "RAW"
      bat:
        what: bat
        where:
          ref: matrix_inner_bottom
          shift: [1.75cx, -1.2cy]
          rotate: 180
        params:
          neg: GND
      vias:
        what: via
        where: true
        adjust:
          shift: [2, 2.5]
        params:
          net: "{{column_net}}"
cases:
  bottom:
    - name: smooth1
      extrude: 1
