const m = require('makerjs')
const a = require('./assert')
const o = require('./operation')
const jscad_utils = require('./jscad_utils')

exports.parse = (config, outlines, units) => {

    const cases_config = a.sane(config, 'cases', 'object')()

    const scripts = {}
    const cases = {}
    const results = {}

    const resolve = (case_name, resolved_scripts = new Set(), resolved_cases = new Set()) => {
        for (const o of Object.values(cases[case_name].outline_dependencies)) {
            resolved_scripts.add(o)
        }
        for (const c of Object.values(cases[case_name].case_dependencies)) {
            resolved_cases.add(c)
            resolve(c, resolved_scripts, resolved_cases)
        }
        const result = []

        // Add JSCAD v2 imports at the top
        result.push(`// JSCAD v2 generated by Ergogen
const { booleans, primitives, extrusions, transforms, measurements } = require('@jscad/modeling')

`)

        for (const o of resolved_scripts) {
            result.push(scripts[o] + '\n')
        }
        for (const c of resolved_cases) {
            result.push(cases[c].body)
        }
        result.push(cases[case_name].body)
        result.push(`
        
            function main() {
                return ${case_name}_case_fn();
            }

            module.exports = { main }

        `)
        return result.join('')
    }

    for (let [case_name, case_config] of Object.entries(cases_config)) {

        // config sanitization
        if (a.type(case_config)() == 'array') {
            case_config = { ...case_config }
        }
        const parts = a.sane(case_config, `cases.${case_name}`, 'object')()

        const body = []
        const case_dependencies = []
        const outline_dependencies = []
        let unionParts = null
        let subtractParts = null
        let intersectParts = null
        for (let [part_name, part] of Object.entries(parts)) {
            if (a.type(part)() == 'string') {
                part = o.operation(part, {
                    outline: Object.keys(outlines),
                    case: Object.keys(cases)
                }, ['case', 'outline'])
            }
            const part_qname = `cases.${case_name}.${part_name}`
            const part_var = `${case_name}__part_${part_name}`
            a.unexpected(part, part_qname, ['what', 'name', 'extrude', 'shift', 'rotate', 'operation'])
            const what = a.in(part.what || 'outline', `${part_qname}.what`, ['outline', 'case'])
            const name = a.sane(part.name, `${part_qname}.name`, 'string')()
            const shift = a.numarr(part.shift || [0, 0, 0], `${part_qname}.shift`, 3)(units)
            const rotate = a.numarr(part.rotate || [0, 0, 0], `${part_qname}.rotate`, 3)(units)
            const operation = a.in(part.operation || 'add', `${part_qname}.operation`, ['add', 'subtract', 'intersect'])

            let base
            if (what == 'outline') {
                const extrude = a.sane(part.extrude || 1, `${part_qname}.extrude`, 'number')(units)
                const outline = outlines[name]
                a.assert(outline, `Field "${part_qname}.name" does not name a valid outline!`)
                // This is a hack to separate multiple calls to the same outline with different extrude values
                // I know it needlessly duplicates a lot of code, but it's the quickest fix in the short term
                // And on the long run, we'll probably be moving to CADQuery anyway...
                const extruded_name = `${name}_extrude_` + ('' + extrude).replace(/\D/g, '_')
                if (!scripts[extruded_name]) {
                    scripts[extruded_name] = jscad_utils.modelToJscadV2(outline, {
                        functionName: `${extruded_name}_outline_fn`,
                        extrude: extrude,
                        indent: 4
                    })
                }
                outline_dependencies.push(extruded_name)
                base = `${extruded_name}_outline_fn()`
            } else {
                a.assert(part.extrude === undefined, `Field "${part_qname}.extrude" should not be used when what=case!`)
                a.in(name, `${part_qname}.name`, Object.keys(cases))
                case_dependencies.push(name)
                base = `${name}_case_fn()`
            }

            // Track parts by operation type
            if (operation == 'add') {
                if (!unionParts) unionParts = []
                unionParts.push(part_var)
            } else if (operation == 'subtract') {
                if (!subtractParts) subtractParts = []
                subtractParts.push(part_var)
            } else if (operation == 'intersect') {
                if (!intersectParts) intersectParts = []
                intersectParts.push(part_var)
            }

            body.push(`

                // creating part ${part_name} of case ${case_name}
                let ${part_var} = ${base};

                // make sure that rotations are relative to the center
                const ${part_var}_bounds = measurements.measureBoundingBox(${part_var});
                const ${part_var}_bounds_center = [
                    (${part_var}_bounds[0][0] + ${part_var}_bounds[1][0]) / 2,
                    (${part_var}_bounds[0][1] + ${part_var}_bounds[1][1]) / 2,
                    (${part_var}_bounds[0][2] + ${part_var}_bounds[1][2]) / 2
                ];
                
                // translate to origin for rotation
                ${part_var} = transforms.translate([-${part_var}_bounds_center[0], -${part_var}_bounds_center[1], -${part_var}_bounds_center[2]], ${part_var});
                
                // apply rotation
                if (${JSON.stringify(rotate)}[0] !== 0) ${part_var} = transforms.rotateX(${JSON.stringify(rotate)}[0] * Math.PI / 180, ${part_var});
                if (${JSON.stringify(rotate)}[1] !== 0) ${part_var} = transforms.rotateY(${JSON.stringify(rotate)}[1] * Math.PI / 180, ${part_var});
                if (${JSON.stringify(rotate)}[2] !== 0) ${part_var} = transforms.rotateZ(${JSON.stringify(rotate)}[2] * Math.PI / 180, ${part_var});
                
                // translate back from origin
                ${part_var} = transforms.translate([${part_var}_bounds_center[0], ${part_var}_bounds_center[1], ${part_var}_bounds_center[2]], ${part_var});

                // apply additional shift
                ${part_var} = transforms.translate(${JSON.stringify(shift)}, ${part_var});
                
            `)
        }

        // Add final combination logic
        body.push(`
                // combine all parts using JSCAD v2 boolean operations
`)

        // Build result from operations
        if (unionParts && unionParts.length > 0) {
            if (unionParts.length === 1) {
                body.push(`                let result = ${unionParts[0]};\n`)
            } else {
                body.push(`                let result = booleans.union(${unionParts.join(', ')});\n`)
            }
        } else {
            // No union parts - shouldn't happen but handle gracefully
            body.push(`                let result = primitives.cube({size: 1});\n`)
        }

        if (subtractParts && subtractParts.length > 0) {
            body.push(`                result = booleans.subtract(result, ${subtractParts.join(', ')});\n`)
        }

        if (intersectParts && intersectParts.length > 0) {
            if (intersectParts.length === 1) {
                body.push(`                result = booleans.intersect(result, ${intersectParts[0]});\n`)
            } else {
                body.push(`                result = booleans.intersect(result, booleans.union(${intersectParts.join(', ')}));\n`)
            }
        }

        cases[case_name] = {
            body: `

                function ${case_name}_case_fn() {
                    ${body.join('')}
                    return result;
                }
            
            `,
            case_dependencies,
            outline_dependencies
        }

        results[case_name] = resolve(case_name)
    }

    return results
}